language: node_js
node_js: '6.3.0'
sudo: required
dist: trusty
before_install:
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository -y ppa:wine/wine-builds
  - sudo apt-get -qq update
  - sudo apt-get install -y --install-recommends winehq-staging
script: "wine --version"
