language: node_js
node_js:
  - '6.3.0'
addons:
  apt:
    packages:
    - wine
cache: apt
sudo: false
install: ""
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export WINEDLLOVERRIDES=\"mscoree,mshtml=\""
  - "timeout 3s WINEDEBUG=+all wine cmd /C echo Wine is working > fail.log 2>&1"
  - "tail -n 20 fail.log"
