language: node_js
node_js:
  - '6.3.0'
addons:
  apt:
    packages:
      - wine
      - moreutils
sudo: false
dist: trusty
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export WINEDLLOVERRIDES=\"mscoree,mshtml=\""
  - "echo Configuring Wine... | ts"
  - "wine cmd /C \"echo > wine_ready\" &"
  - "COUNTER=20"
  - "until [ $COUNTER -eq 0 ] || [ -f wine_ready ]; do echo Waiting... | ts; sleep 60; let COUNTER-=1; done"
  - "[ -f wine_ready ]"
  - "./node_modules/.bin/electron-packager . relief-valve --platform=win32 --arch=x64"
