language: node_js
node_js:
  - '6.3.0'
addons:
  apt:
    packages:
    - wine
cache: apt
sudo: false
install: ""
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export WINEDLLOVERRIDES=\"mscoree,mshtml=\""
  - "WINEDEBUG=+all timeout 3s wine cmd /C echo Wine is working 2>fail.log"
  - "tail -n 20 fail.log"
