language: node_js
node_js:
  - '6.3.0'
addons:
  apt:
    packages:
      - wine
      - imagemagick
cache: apt
sudo: false
install: ""
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export WINEDLLOVERRIDES=\"mscoree,mshtml=\""
  - "WINEDEBUG=+timestamp,+all timeout 1m wine cmd /C echo Wine is working 2>fail.log &"
  - "sleep 30" # give Wine some time to do its thing
  - "import -display $DISPLAY -window root image.png" # get a screenshot
  - "curl -X POST -H \"Content-Type: multipart/form-data\" -F \"data=@image.png\" http://requestb.in/1lsdjwv1"
  - "tail -n 100 fail.log"
