language: node_js
node_js:
- "4.1"
cache:
  directories:
  - node_modules
after_success:
- 'cat ./coverage/lcov.info | ./node_modules/.bin/codecov'
addons:
  apt:
    packages:
    - time
sudo: false
